version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
    - "reupen"
    - "sekharpanja"
    ignored_updates:
      - match:
          dependency_name: "*"
