name: Create release PR

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  create_release_pr:
    if: github.event.pull_request.merged && startsWith(github.event.pull_request.head.label, 'uktrade:changelog/')

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --progress-bar off requests

    - name: Run release PR script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python scripts/prepare_release.py
