name: Publish release

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  publish_release:
    if: github.event.pull_request.merged && startsWith(github.event.pull_request.head.label, 'uktrade:release/')
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --progress-bar off -r requirements.txt

      - name: Run publish release script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/publish_release.py
